
image:
  file: .gitpod.Dockerfile
tasks: 
  - init: |
      git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
      git config --global alias.co checkout
      git config --global alias.br branch
      git config --global alias.ci commit
      git config --global alias.st status  
      eval "$(pandoc --bash-completion)"
      # sudo apt-get -q update &&  sudo apt-get install -yq texlive &&  sudo apt-get install  texlive-latex-extra &&  sudo rm -rf /var/lib/apt/lists/*
      # brew install pandoc
  - command: echo hello

vscode:
  extensions:
    - bringout.pdf-view
